export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_IS_LOADING = "GET_GAMES_IS_LOADING";
export const GET_GAMES_HAS_ERRORED = "GET_GAMES_HAS_ERRORED";
export const CREATE_NEW_GAME_SUCCESS = "CREATE_NEW_GAME_SUCCESS";
export const CREATE_NEW_GAME_IS_LOADING = "CREATE_NEW_GAME_IS_LOADING";
export const CREATE_NEW_GAME_HAS_ERRORED = "CREATE_NEW_GAME_HAS_ERRORED";
export const GET_GAME_SUCCESS = "GET_GAME_SUCCESS";
export const GET_GAME_IS_LOADING = "GET_GAME_IS_LOADING";
export const GET_GAME_HAS_ERRORED = "GET_GAME_HAS_ERRORED";

